# permissions for end users to edit miniousers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: miniouser-editor-role
rules:
- apiGroups:
  - minio.walkbase.com
  resources:
  - miniousers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.walkbase.com
  resources:
  - miniousers/status
  verbs:
  - get
