# permissions for end users to edit miniobuckets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: miniobucket-editor-role
rules:
- apiGroups:
  - minio.walkbase.com
  resources:
  - miniobuckets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - minio.walkbase.com
  resources:
  - miniobuckets/status
  verbs:
  - get
