namespace: default
namePrefix: mro-
bases:
- ../crd
- ../rbac
- ../manager

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml
- envpatch.yaml

patchesJson6902:
- target:
    group: "apps" 
    version: v1 # apiVersion
    kind: Deployment
    name: controller-manager
  path: vaultpath.yaml
